server:
  port: 8080
  contextPath: /foodapp
---
spring:
  profiles: default, production
  datasource:
    initialize: false
datasource:
  properties:
    url: jdbc:mysql://localhost:3306/ds_proj
    username: <YOUR-USERNAME>
    password: <YOUR-PASSWORD>
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: none
      show_sql: false
      format_sql: false
      dialect: org.hibernate.dialect.MySQLDialect
routes:
  apiKey: <YOUR-API-KEY>
  startAddress: Strada Observatorului 33, Cluj-Napoca 400000, Romania
  baseUrl: https://maps.googleapis.com/maps/api/directions/json
---
spring:
  profiles: test
  datasource:
    initialize: false
datasource:
  properties:
    url: jdbc:h2:~/test
    username: "SA"
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: false
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect